const secretType = "'{.SECRET_TYPE}'"
const secretExt  = "'{.SECRET_EXTENSION}'"
const saltSize   = '{.SALT_SIZE}'  // bytes
const blockSize  = '{.BLOCK_SIZE}' // bytes
const keySize    = '{.KEY_SIZE}'   // bytes
const iterations = '{.ITERATIONS}'
const saltHex    = "'{.SALT_HEX}'"
const ivHex      = "'{.IV_HEX}'"
const cipherHex  = "'{.CIPHER_HEX}'"
